groups:
  - name: "system_alerts"
    rules:
      - alert: "NodeUnreachable"
        expr: "up{job='node-exporter'} == 0"
        for: "1m"
        labels:
          severity: "critical"
        annotations:
          summary: "Node {{ $labels.nodename }} is unreachable"
          description: "The monitoring agent on {{ $labels.nodename }} ({{ $labels.instance }}) has been down for more than 1 minute. The host might be powered off or network isolated."

      - alert: "HighCpuUsage"
        expr: "100 - (avg by(instance, nodename, environment) (rate(node_cpu_seconds_total{mode='idle'}[2m])) * 100) > 85"
        for: "2m"
        labels:
          severity: "warning"
        annotations:
          summary: "High CPU usage on {{ $labels.nodename }}"
          description: "CPU usage on node {{ $labels.nodename }} is currently {{ $value | printf \"%.2f\" }}%."

      - alert: "HighMemoryUsage"
        expr: "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 > 90"
        for: "2m"
        labels:
          severity: "warning"
        annotations:
          summary: "High memory usage on {{ $labels.nodename }}"
          description: "Memory usage on node {{ $labels.nodename }} is currently {{ $value | printf \"%.2f\" }}%."
