---
- targets:
  - "node-exporter:9100"
  labels:
    nodename: "vmpipe"
    environment: "vmpipe"
    job: "node-exporter"
- targets:
  - "cadvisor:8080"
  labels:
    nodename: "vmpipe"
    environment: "vmpipe"
    job: "cadvisor"
- targets:
  - "filebeat:5066"
  labels:
    nodename: "vmpipe"
    environment: "vmpipe"
    job: "filebeat"
