- targets:
  - http://backend:8880/actuator/health
  labels:
    job: blackbox
    environment: central-node
    nodename: central-node
    probe_module: http_2xx
    target_type: node
- targets:
  - http://frontend:80
  labels:
    job: blackbox
    environment: central-node
    nodename: central-node
    probe_module: http_2xx
    target_type: frontend
- targets:
  - http://192.168.126.131:80
  labels:
    environment: test
    job: blackbox
    nodename: node-192-168-126-131
    probe_module: http_2xx
    target_type: frontend
- targets:
  - http://192.168.126.135:80
  labels:
    environment: test
    job: blackbox
    nodename: node-192-168-126-135
    probe_module: http_2xx
    target_type: frontend
