filebeat.inputs:
- type: container
  id: docker-container-logs
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log

- type: filestream
  id: system-logs
  enabled: false
  paths:
    - /var/log/*.log

processors:
  - add_docker_metadata: ~
  - add_host_metadata: ~
  - add_fields:
      target: ''
      fields:
        node: "vmpipe"

output.logstash:
  hosts: ["logstash:5045"]

logging.level: info
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

monitoring.enabled: true
monitoring.prometheus.enabled: true
monitoring.prometheus.host: 0.0.0.0
monitoring.prometheus.port: 5066
