filebeat.inputs:
  - type: container
    id: docker-container-logs
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container: ~

fields:
  environment: "{{ env_label }}"
  node: "{{ nodename }}"
fields_under_root: true

strict.perms: false

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_host_metadata: ~

output.logstash:
  hosts: ["{{ central_logstash_ip }}:5045"]

logging.level: info

http.enabled: true
http.host: 0.0.0.0
http.port: 5066
