[agents:children]
# Placeholder for dynamic generation by backend
# Example: 192.168.1.50 ansible_user=root
vmpipe
pre-prod

[vmpipe]
192.168.126.130 ansible_user=root
root ansible_host=192.168.126.130 ansible_user=root

[pre-prod]
