---
- targets:
  - "192.168.126.130:9100"
  labels:
    environment: "vmpipe"
    job: "node-exporter"
    nodename: "vmpipe"
- targets:
  - "192.168.126.130:8085"
  labels:
    environment: "vmpipe"
    job: "cadvisor"
    nodename: "vmpipe"
- targets:
  - "192.168.126.130:5066"
  labels:
    environment: "vmpipe"
    job: "filebeat"
    nodename: "vmpipe"
